//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Carts = new HashSet<Cart>();
            this.Images = new HashSet<Image>();
        }

        public int PropertyId { get; set; }
        [Required(ErrorMessage = "PropertyName is compulsory field")]
        public string PropertyName { get; set; }
        [Required(ErrorMessage = "PropertyType is compulsory field")]
        public string PropertyType { get; set; }
        [Required(ErrorMessage = "Description is compulsory field")]
        public string Descript { get; set; }
        [Required(ErrorMessage = "Address is compulsory field")]
        public string Adress { get; set; }
        [Required(ErrorMessage = "PriceRange is compulsory field")]
        public Nullable<decimal> PriceRange { get; set; }
        [Required(ErrorMessage = "InitialDeposit is compulsory field")]
        public Nullable<decimal> InitialDeposit { get; set; }
        [Required(ErrorMessage = "Landmark is compulsory field")]
        public string LandMark { get; set; }
        [Required(ErrorMessage = "IsActive is compulsory field")]
        public bool IsActive { get; set; }
        [Required(ErrorMessage = "SellerId is compulsory field")]
        public int SellerId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
