//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller()
        {
            this.Properties = new HashSet<Property>();
        }

        //[Required(ErrorMessage = "SellerId is compulsory field")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SellerId { get; set; }
        [Required(ErrorMessage = "Username is compulsory field")]
        [DisplayName("Username")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "First name is compulsory field")]
        [DisplayName("First name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last name is compulsory field")]
        [DisplayName("Last name")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Date of Birth is compulsory field")]
        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Contact number is compulsory field")]
        [DisplayName("Contact number")]
        [StringLength(10, MinimumLength = 10)]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Address is compulsory field")]
        [DisplayName("Address")]
        public string Adress { get; set; }
        [Required(ErrorMessage = "State name is compulsory field")]
        [DisplayName("State name")]
        //[ForeignKey("State")]
        public int StateId { get; set; }
        [DisplayName("City name")]
        [Required(ErrorMessage = "City name is compulsory field")]
        //[ForeignKey("City")]
        public int CityId { get; set; }
        [Required(ErrorMessage = "Email address is compulsory field")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        [DisplayName("Email Id")]
        public string EmailId { get; set; }

        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        public virtual State State { get; set; }
    }
}
